river:
  email: rivercomsci09@gmail.com
  googleAnalyticsId: U-xxxxx
  authors:
    - river
    - atom
  exampleMap:
      key1: hello
      key2: world

#application.yml
---
spring.profiles: local
spring.profiles.include: common, local
---
spring.profiles: aws
spring.profiles.include: common, aws
---